services:
  - type: web
    name: journix
    env: node
    region: singapore
    plan: free
    rootDir: .
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install && npx prisma generate && npm run build
    startCommand: cd backend && npx prisma migrate deploy && npx ts-node prisma/seed.ts ; node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./prisma/dev.db
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
